services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: extension-api:local
    ports:
      - '${APP_PORT:-80}:80'
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - public_build:/var/www/html/public/build
    restart: unless-stopped

volumes:
  vendor_data:
    driver: local
  public_build:
    driver: local
